CREATE SCHEMA IF NOT EXISTS liquibase;

GRANT ALL PRIVILEGES ON SCHEMA liquibase TO postgres;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA liquibase TO postgres;
ALTER SCHEMA liquibase OWNER TO postgres;