CREATE SCHEMA IF NOT EXISTS liquibase;

CREATE USER liquibase_user WITH PASSWORD 'liquibase_pass';

GRANT ALL PRIVILEGES ON SCHEMA liquibase TO liquibase_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA liquibase TO liquibase_user;
ALTER SCHEMA liquibase OWNER TO liquibase_user;

GRANT ALL PRIVILEGES ON SCHEMA public TO liquibase_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO liquibase_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO liquibase_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO liquibase_user;