spring:
  application:
    name: taskCatalog
  datasource:
    url: jdbc:postgresql://localhost:5435/taskdb
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs