spring:
  application:
    name: taskCatalog
  datasource:
    url: jdbc:postgresql://localhost:5432/taskdb?currentSchema=public
    username: task_user
    password: task_pass
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
server:
  port: 8080
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs
#logging:
#  level:
#    org:
#      springframework:
#        jdbc:
#          core:
#            JdbcTemplate: DEBUG