ALTER SCHEMA public OWNER TO task_user;

GRANT ALL PRIVILEGES ON SCHEMA public TO task_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO task_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO task_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO task_user;
